### ISSUE TITLE
Upgrade Brew

### ISSUE THREAD

**Issue by arnaudgs** [clakech/macbook-pro-setup#10]
`brew update` only update homebrew, if you want to upgrade all dependencies, you can type `brew upgrade`

then in the terminal to upgrade all : 
```
brew update && brew upgrade
```

Or if you have installe ohmyzsh you can use `bubu` 
or other shortcuts, check the code here :
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/brew/brew.plugin.zsh

**Comment by clakech** [comment]
https://github.com/clakech/macbook-pro-setup/commit/ce69ed0416ea65750cd5d75b050fdd9f514f7b9e
🎉
